/home/alex/miniconda3/envs/Graph_Praktikum/bin/python /home/alex/PycharmProjects/FitchFriends/fitch_graph_praktikum/state_2024_01_12.py 
#####
Running benchmark 1/3
#####
Multiprocessing on 15 cores:
Calls:  99%|█████████▊| 3453/3500 [1:43:07<02:54,  3.71s/it]3403 generated an exception: maximum recursion depth exceeded while calling a Python object
Calls:  99%|█████████▉| 3478/3500 [1:44:42<01:10,  3.21s/it]3378 generated an exception: maximum recursion depth exceeded while calling a Python object
Calls: 100%|██████████| 3500/3500 [1:51:57<00:00,  1.92s/it] 
3425 generated an exception: maximum recursion depth exceeded while calling a Python object
#####
Running benchmark 2/3
#####
Multiprocessing on 15 cores:
Calls:  51%|█████     | 1776/3500 [16:57<49:37,  1.73s/it]1680 generated an exception: maximum recursion depth exceeded while calling a Python object
Calls: 100%|██████████| 3500/3500 [1:51:41<00:00,  1.91s/it]
#####
Running benchmark 3/3
#####
Multiprocessing on 15 cores:
Calls:  68%|██████▊   | 2389/3500 [40:12<45:26,  2.45s/it]1988 generated an exception: maximum recursion depth exceeded while calling a Python object
Calls:  95%|█████████▌| 3327/3500 [1:57:01<13:19,  4.62s/it]2882 generated an exception: maximum recursion depth exceeded while calling a Python object
Calls: 100%|██████████| 3500/3500 [2:20:23<00:00,  2.41s/it] 

Process finished with exit code 0
