/home/alex/miniconda3/envs/Graph_Praktikum/bin/python /home/alex/PycharmProjects/FitchFriends/fitch_graph_praktikum/state_2024_01_12.py 
#####
Running benchmark 1/3
#####
Multiprocessing on 15 cores:
Calls:  71%|███████   | 2470/3500 [39:55<32:08,  1.87s/it]2128 generated an exception: maximum recursion depth exceeded while calling a Python object
Calls:  91%|█████████ | 3169/3500 [1:26:29<13:59,  2.54s/it]2959 generated an exception: maximum recursion depth exceeded while calling a Python object
Calls:  95%|█████████▍| 3312/3500 [1:35:11<13:29,  4.30s/it]2371 generated an exception: maximum recursion depth exceeded while calling a Python object
Calls: 100%|██████████| 3500/3500 [1:49:56<00:00,  1.88s/it]
3343 generated an exception: maximum recursion depth exceeded while calling a Python object
#####
Running benchmark 2/3
#####
Multiprocessing on 15 cores:
Calls:  27%|██▋       | 945/3500 [04:01<30:44,  1.39it/s]749 generated an exception: maximum recursion depth exceeded while calling a Python object
Calls: 100%|██████████| 3500/3500 [1:45:28<00:00,  1.81s/it]
#####
Running benchmark 3/3
#####
Multiprocessing on 15 cores:
Calls:  62%|██████▏   | 2177/3500 [29:58<1:58:47,  5.39s/it]1881 generated an exception: maximum recursion depth exceeded while calling a Python object
Calls:  96%|█████████▋| 3376/3500 [1:55:52<08:14,  3.99s/it]2923 generated an exception: maximum recursion depth exceeded while calling a Python object
Calls:  98%|█████████▊| 3430/3500 [2:00:26<03:13,  2.77s/it]
